# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff4425119a5a0a5d2a7ed3d132ee2d0dc2e2112a5717faf26f18b76c8bc50aa62a7865555fc78c17425ad4d0df59924ea816b5f0542bde1ae3558ea6cf38b1da

test:
  secret_key_base: 75dc04ce54ed9c123a833be65b9415999b7643839e4eaf257147498636add046d3c532e9ee8087f7d0c621a4eab754dde85226964215242be8dd9e28bcfed050

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
